apiVersion: v1
kind: LimitRange
metadata:
  name: dev-limits
  namespace: ns-dev
spec:
  limits:
  - type: Container
    max:
      cpu: "200m"
      memory: "256Mi"
    default: 
      cpu: "200m"
      memory: "256Mi"
    defaultRequest: 
      cpu: "100m"
      memory: "128Mi"
