apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-quota
  namespace: ns-dev
spec:
  hard:
    pods: "10"                 
    requests.cpu: "1000m"      
    requests.memory: "1Gi"
    limits.cpu: "1000m"        
    limits.memory: "1Gi"
