apiVersion: v1
kind: ResourceQuota
metadata:
  name: prod-quota
  namespace: ns-prod
spec:
  hard:
    requests.cpu: "2000m"      
    requests.memory: "2Gi"
    limits.cpu: "2000m"        
    limits.memory: "2Gi"
